name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check src

      - name: Analyze code
        run: make lint

      - name: Install deps
        run: make reload.dependencies

      - name: Run unit and integration tests
        run: make test

      - name: Generate coverage report
        run: make coverage
